version: '2.2'

services: 
    music_streaming_bot:
        image: music_streaming_bot
        build: .
        environment: 
            NODE_ENV: production
        ports: 
            - 8080:8080
        volumes:
            - .:/usr/src/app
