version: "3.8"

services: 
    music_streaming_bot:
        image: music_streaming_bot
        build: .
        environment: 
            NODE_ENV: production
        ports: 
            - 8080:8080
        command: "npm run start"
        volumes:
            - .:/usr/src/app
